version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: gafri
      MYSQL_DATABASE: golang
      MYSQL_USER: gafri
      MYSQL_PASSWORD: gafri
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - backend

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend
    environment:
        - MYSQL_HOST: 127.0.0.1
        - MYSQL_PORT: 3306
        - MYSQL_DATABASE: golang
        - MYSQL_USER: gafri
        - MYSQL_PASSWORD: gafri

networks:
  backend:
  
volumes:
  dbdata: